package myung.jin.bikerepairdoc.ui.theme

import androidx.compose.ui.graphics.Color

// Modern Professional Palette - Navy & Steel
val primaryLight = Color(0xFF00668B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC3E7FF)
val onPrimaryContainerLight = Color(0xFF001D2D)
val secondaryLight = Color(0xFF4E606F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD2E5F6)
val onSecondaryContainerLight = Color(0xFF0A1D2A)
val tertiaryLight = Color(0xFF635A7C)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE9DDFF)
val onTertiaryContainerLight = Color(0xFF1F1835)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF8F9FF)
val onBackgroundLight = Color(0xFF191C1E)
val surfaceLight = Color(0xFFF8F9FF)
val onSurfaceLight = Color(0xFF191C1E)
val surfaceVariantLight = Color(0xFFDDE3EA)
val onSurfaceVariantLight = Color(0xFF41474D)
val outlineLight = Color(0xFF71787E)
val outlineVariantLight = Color(0xFFC1C7CE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3133)
val inverseOnSurfaceLight = Color(0xFFF0F1F4)
val inversePrimaryLight = Color(0xFF7CD0FF)
val surfaceDimLight = Color(0xFFD8DADD)
val surfaceBrightLight = Color(0xFFF8F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F4F7)
val surfaceContainerLight = Color(0xFFECEEF2)
val surfaceContainerHighLight = Color(0xFFE7E9EC)
val surfaceContainerHighestLight = Color(0xFFE1E3E6)

// Dark Mode Palette
val primaryDark = Color(0xFF7CD0FF)
val onPrimaryDark = Color(0xFF00344A)
val primaryContainerDark = Color(0xFF004C6A)
val onPrimaryContainerDark = Color(0xFFC3E7FF)
val secondaryDark = Color(0xFFB6C9DA)
val onSecondaryDark = Color(0xFF20323F)
val secondaryContainerDark = Color(0xFF374956)
val onSecondaryContainerDark = Color(0xFFD2E5F6)
val tertiaryDark = Color(0xFFCDC2E9)
val onTertiaryDark = Color(0xFF342D4B)
val tertiaryContainerDark = Color(0xFF4B4363)
val onTertiaryContainerDark = Color(0xFFE9DDFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF191C1E)
val onBackgroundDark = Color(0xFFE1E3E6)
val surfaceDark = Color(0xFF191C1E)
val onSurfaceDark = Color(0xFFE1E3E6)
val surfaceVariantDark = Color(0xFF41474D)
val onSurfaceVariantDark = Color(0xFFC1C7CE)
val outlineDark = Color(0xFF8B9198)
val outlineVariantDark = Color(0xFF41474D)

// Extended Colors
val customColor1Light = Color(0xFF006781)
val onCustomColor1Light = Color(0xFFFFFFFF)
val customColor1ContainerLight = Color(0xFFBAEAFF)
val onCustomColor1ContainerLight = Color(0xFF001F29)
val customColor1Dark = Color(0xFF5DD5FC)
val onCustomColor1Dark = Color(0xFF003544)
val customColor1ContainerDark = Color(0xFF004D62)
val onCustomColor1ContainerDark = Color(0xFFBAEAFF)
